apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: desafio
    pod-template-hash: 86f5f77bdf
  name: desafio-86f5f77bdf-ltnp9
  namespace: virt
spec:
  ports:
  - port: 4000
    protocol: TCP
    targetPort: 4000
  selector:
    app: desafio
    pod-template-hash: 86f5f77bdf
  type: NodePort
status:
  loadBalancer: {}
